In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#import dataset from data.csv file

In [2]:
dataset = pd.read_csv('data.csv')
dataset = dataset.fillna(0)

In [3]:
dataset

date  pm25  pm10   o3  no2  so2   co
0      2020/5/1   110    54   50    1    2    4
1      2020/5/2    68    71   36    1    3    2
2      2020/5/3    81    74   38    1    3    4
3      2020/5/4    77    49   37    2    2    4
4      2020/5/5    62    70   36    3    3    5
..          ...   ...   ...  ...  ...  ...  ...
533  2019/12/31         104   25   10    2   12
534    2019/6/1          87   44    3    3    7
535  2018/12/31         171   59   27    5   14
536  2018/11/29         108   62   13    2    9
537  2018/12/14          90   53   11    2    6

[538 rows x 7 columns]

In [4]:
dataset=dataset.reset_index(drop=True)

In [5]:
training_set = dataset.iloc[:,4:5].values

In [6]:
training_set1=[]
for i in training_set:
    if i!=' ':
        training_set1.append(int(i[0].strip()))

In [7]:
training_set1 = np.array(training_set1)

In [8]:
training_set1 = training_set1.reshape(-1,1)

In [9]:
tested = training_set1[30:60]
training_set1 = training_set1[:60]

In [10]:
#Feature Scaling 
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set1)

In [11]:
testing = sc.transform(tested)
testing = np.array(testing)
testing = np.reshape(testing,(testing.shape[1],testing.shape[0],1))

In [12]:
training_set_scaled

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.07692308],
       [0.15384615],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.15384615],
       [0.15384615],
       [0.23076923],
       [0.15384615],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.        ],
       [0.        ],
       [0.07692308],
       [0.23076923],
       [0.23076923],
       [0.23076923],
       [0.38461538],
       [0.30769231],
       [0.23076923],
       [0.15384615],
       [0.23076923],
       [0.30769231],
       [0.46153846],
       [0.30769231],
       [0.38461538],
       [0.46153846],
       [0.38461538],
       [0.23076923],
       [0.23076923],
       [0.30769231],
       [0.15384615],
       [0.38461538],
       [0.30769231],
       [0.30769231],
       [0.30769231],
       [0.15384615],
       [0.07692308],
       [0.076

In [13]:
training_set_scaled

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.07692308],
       [0.15384615],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.15384615],
       [0.15384615],
       [0.23076923],
       [0.15384615],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.07692308],
       [0.        ],
       [0.        ],
       [0.07692308],
       [0.23076923],
       [0.23076923],
       [0.23076923],
       [0.38461538],
       [0.30769231],
       [0.23076923],
       [0.15384615],
       [0.23076923],
       [0.30769231],
       [0.46153846],
       [0.30769231],
       [0.38461538],
       [0.46153846],
       [0.38461538],
       [0.23076923],
       [0.23076923],
       [0.30769231],
       [0.15384615],
       [0.38461538],
       [0.30769231],
       [0.30769231],
       [0.30769231],
       [0.15384615],
       [0.07692308],
       [0.076

In [14]:
tested

array([[ 4],
       [ 5],
       [ 7],
       [ 5],
       [ 6],
       [ 7],
       [ 6],
       [ 4],
       [ 4],
       [ 5],
       [ 3],
       [ 6],
       [ 5],
       [ 5],
       [ 5],
       [ 3],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 4],
       [ 4],
       [ 3],
       [13],
       [14],
       [ 8],
       [10],
       [ 7],
       [10],
       [ 8]])

In [15]:
x_train = []
y_train = []
n_future = 4 # next 4 days temperature forecast
n_past = 30 # Past 30 days 

In [16]:
for i in range(0,len(training_set_scaled)-n_past-n_future+1):
    x_train.append(training_set_scaled[i : i + n_past , 0])     
    y_train.append(training_set_scaled[i + n_past : i + n_past + n_future , 0 ])

In [17]:
x_train , y_train = np.array(x_train), np.array(y_train)

In [18]:
x_train

array([[0.        , 0.        , 0.        , 0.07692308, 0.15384615,
        0.07692308, 0.07692308, 0.07692308, 0.07692308, 0.07692308,
        0.15384615, 0.15384615, 0.23076923, 0.15384615, 0.07692308,
        0.07692308, 0.07692308, 0.07692308, 0.07692308, 0.07692308,
        0.        , 0.        , 0.07692308, 0.23076923, 0.23076923,
        0.23076923, 0.38461538, 0.30769231, 0.23076923, 0.15384615],
       [0.        , 0.        , 0.07692308, 0.15384615, 0.07692308,
        0.07692308, 0.07692308, 0.07692308, 0.07692308, 0.15384615,
        0.15384615, 0.23076923, 0.15384615, 0.07692308, 0.07692308,
        0.07692308, 0.07692308, 0.07692308, 0.07692308, 0.        ,
        0.        , 0.07692308, 0.23076923, 0.23076923, 0.23076923,
        0.38461538, 0.30769231, 0.23076923, 0.15384615, 0.23076923],
       [0.        , 0.07692308, 0.15384615, 0.07692308, 0.07692308,
        0.07692308, 0.07692308, 0.07692308, 0.15384615, 0.15384615,
        0.23076923, 0.15384615, 0.07692308, 0.

In [19]:
x_train.shape[1]

30

In [20]:
x_train = np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1) )

In [21]:
from keras.models import Sequential
from keras.layers import LSTM,Dense ,Dropout
# Fitting RNN to training set using Keras Callbacks. Read Keras callbacks docs for more info.

Using TensorFlow backend.


In [22]:
regressor = Sequential()
regressor.add((LSTM(units=30, return_sequences=True, input_shape = (x_train.shape[1],1) ) ))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units= 30 , return_sequences=True))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units= 30 , return_sequences=True))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units= 30))
regressor.add(Dropout(0.2))
regressor.add(Dense(units = n_future,activation='linear'))
regressor.compile(optimizer='adam', loss='mean_squared_error',metrics=['acc'])
regressor.fit(x_train, y_train, epochs=500,batch_size=32 )

Epoch 1/500
27/27 [==============================] - 2s 56ms/step - loss: 0.1802 - acc: 0.2963
Epoch 2/500
27/27 [==============================] - 0s 1ms/step - loss: 0.1670 - acc: 0.3704
Epoch 3/500
27/27 [==============================] - 0s 1ms/step - loss: 0.1542 - acc: 0.3333
Epoch 4/500
27/27 [==============================] - 0s 1ms/step - loss: 0.1433 - acc: 0.3704
Epoch 5/500
27/27 [==============================] - 0s 1ms/step - loss: 0.1286 - acc: 0.2963
Epoch 6/500
27/27 [==============================] - 0s 1ms/step - loss: 0.1144 - acc: 0.2593
Epoch 7/500
27/27 [==============================] - 0s 955us/step - loss: 0.1011 - acc: 0.2963
Epoch 8/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0914 - acc: 0.2963
Epoch 9/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0731 - acc: 0.3333
Epoch 10/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0623 - acc: 0.1852
Epoch 11/500
27/27 [==============================] - 0s

Epoch 88/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0394 - acc: 0.3333
Epoch 89/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0359 - acc: 0.3333
Epoch 90/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0331 - acc: 0.2963
Epoch 91/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0356 - acc: 0.4815
Epoch 92/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0457 - acc: 0.3333
Epoch 93/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0289 - acc: 0.2963
Epoch 94/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0366 - acc: 0.1481
Epoch 95/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0346 - acc: 0.3333
Epoch 96/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0405 - acc: 0.2593
Epoch 97/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0369 - acc: 0.1481
Epoch 98/500
27/27 [==============================

Epoch 174/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0284 - acc: 0.2593
Epoch 175/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0317 - acc: 0.4074
Epoch 176/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0259 - acc: 0.3333
Epoch 177/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0270 - acc: 0.2963
Epoch 178/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0268 - acc: 0.3704
Epoch 179/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0266 - acc: 0.3333
Epoch 180/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0238 - acc: 0.3333
Epoch 181/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0261 - acc: 0.4074
Epoch 182/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0291 - acc: 0.3333
Epoch 183/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0234 - acc: 0.2963
Epoch 184/500
27/27 [===================

Epoch 260/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0216 - acc: 0.3704
Epoch 261/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0192 - acc: 0.3704
Epoch 262/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0246 - acc: 0.4815
Epoch 263/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0196 - acc: 0.5185
Epoch 264/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0183 - acc: 0.5185
Epoch 265/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0179 - acc: 0.5556
Epoch 266/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0237 - acc: 0.4444
Epoch 267/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0208 - acc: 0.6296
Epoch 268/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0218 - acc: 0.3333
Epoch 269/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0253 - acc: 0.3333
Epoch 270/500
27/27 [===================

Epoch 346/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0182 - acc: 0.4444
Epoch 347/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0171 - acc: 0.4074
Epoch 348/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0204 - acc: 0.2963
Epoch 349/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0200 - acc: 0.4074
Epoch 350/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0198 - acc: 0.4074
Epoch 351/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0175 - acc: 0.2593
Epoch 352/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0181 - acc: 0.4074
Epoch 353/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0195 - acc: 0.5556
Epoch 354/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0170 - acc: 0.5185
Epoch 355/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0153 - acc: 0.5185
Epoch 356/500
27/27 [===================

Epoch 432/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0181 - acc: 0.4444
Epoch 433/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0160 - acc: 0.4815
Epoch 434/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0190 - acc: 0.5185
Epoch 435/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0170 - acc: 0.4444
Epoch 436/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0165 - acc: 0.5556
Epoch 437/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0185 - acc: 0.4815
Epoch 438/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0170 - acc: 0.6296
Epoch 439/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0184 - acc: 0.5556
Epoch 440/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0215 - acc: 0.5185
Epoch 441/500
27/27 [==============================] - 0s 1ms/step - loss: 0.0168 - acc: 0.5185
Epoch 442/500
27/27 [===================

In [23]:
predicted_temperature = regressor.predict(testing)
predicted_temperature = sc.inverse_transform(predicted_temperature)
predicted_temperature = np.reshape(predicted_temperature,(predicted_temperature.shape[1],predicted_temperature.shape[0]))

In [24]:
predicted_temperature

array([[12.055286 ],
       [ 8.8290415],
       [ 8.163499 ],
       [ 8.459897 ]], dtype=float32)

In [25]:
real_temperature = pd.read_csv('data.csv')
real_temperature = real_temperature.iloc[60:64,4:5].values

In [26]:
real_temperature

array([[' 8'],
       [' 10'],
       [' 9'],
       [' 6']], dtype=object)