In [1]:
import numpy as np
import pandas as pd
from array import array
# Warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Multiple Linear Regression
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings("ignore")
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
from sklearn.model_selection import train_test_split
import bisect
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn import metrics
from sklearn import linear_model
#     print('LinearRegression')
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_predict
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
def model(regressor,X_train, X_test, y_train, y_test):
    print(regressor)
    model1 = regressor.fit(X_train,y_train)
    print('train acc')
    print(model1.score(X_train, y_train))
    print('y_pred')
    y_pred = model1.predict(X_test)
    print('testing acc')
    print(r2_score(y_test,y_pred))
#     print('testing acc')
#     df1=pd.DataFrame(y_pred,columns=['pred'])
#     df1['actual']=X_test
#     print(df1)
#     print('\n')
def multi(X_train, X_test, y_train, y_test):
	from sklearn import linear_model
	regressor = linear_model.LinearRegression()
	model(regressor,X_train, X_test, y_train, y_test)
def decision(X_train, X_test, y_train, y_test):
	from sklearn.tree import DecisionTreeRegressor
	regressor = DecisionTreeRegressor(random_state = 0)
	model(regressor,X_train, X_test, y_train, y_test)
def random(X_train, X_test, y_train, y_test):
	from sklearn.ensemble import RandomForestRegressor
	regressor = RandomForestRegressor(n_estimators = 40, random_state = 0)
	model(regressor,X_train, X_test, y_train, y_test)
def svr(X_train, X_test, y_train, y_test):
	from sklearn.svm import SVR
	regressor = SVR(kernel = 'rbf')
	model(regressor,X_train, X_test, y_train, y_test)
def boost(X_train, X_test, y_train, y_test):
	from sklearn import ensemble
	params = {
    'n_estimators': 1,
    'max_depth': 1,
    'learning_rate': 1,
    'criterion': 'mse'
	}
	regressor = ensemble.GradientBoostingRegressor(**params)
	model(regressor,X_train, X_test, y_train, y_test)
def main(X_train, X_test, y_train, y_test):
	multi(X_train, X_test, y_train, y_test)
	decision(X_train, X_test, y_train, y_test)
	random(X_train, X_test, y_train, y_test)
# 	svr(X_train, X_test, y_train, y_test)	
	boost(X_train, X_test, y_train, y_test)

In [4]:
city_day = pd.read_csv("city_day.csv")

In [5]:
city_day['Date'] =  pd.to_datetime(city_day['Date'],format='%Y-%m-%d')

In [6]:
year = city_day['Date'].dt.year
month = city_day['Date'].dt.month
day = city_day['Date'].dt.day

In [7]:
city_day.insert(loc=1, column='Year', value= year)
city_day.insert(loc=2, column='Month', value= month)
city_day.insert(loc=3, column='Date1', value= day)

In [8]:
city_day_ahm = city_day

In [9]:
# city_day_ahm = city_day[city_day["City"]=='Ahmedabad']

In [10]:
city_day_ahm.

SyntaxError: invalid syntax (<ipython-input-10-06af816f75b2>, line 1)

In [11]:
city_day_ahm.to_csv("ahmedabad1.csv")

In [12]:
city_day_ahm.AQI.isnull().sum()

20128

In [13]:
city_day_ahm.Year.value_counts()

2019    31811
2018    25290
2017    13090
2020    12532
2016     9606
2015     7392
Name: Year, dtype: int64

In [14]:
# city_day_1_ahm = city_day_ahm.dropna(axis=0, how="all", subset=["PM2.5","PM10"], inplace=False)

In [15]:
# city_day_1_ahm

In [16]:
city_day_ahm_copy = city_day_ahm

In [17]:
avg_aqi_month = city_day_ahm.groupby(['Month']).AQI.mean()

In [18]:
avg_aqi_month = list(avg_aqi_month)

In [19]:
avg_aqi_month

[255.15911528150133,
 214.81691096634094,
 162.46811915312654,
 158.41673062164236,
 187.92391713747645,
 159.20813442810768,
 110.65454545454546,
 102.72196776929601,
 106.86170035075997,
 205.2069455406472,
 272.2718197375927,
 266.9148282602625]

In [20]:
# Replacing AQI values with monthly average

# temp = city_day_ahm["AQI"].fillna(avg_aqi_month[city_day_ahm.Month-1] ,inplace = False)

for i in range(len(city_day_ahm)):
    if pd.isna(city_day_ahm["AQI"][i]):      
        city_day_ahm["AQI"][i] = avg_aqi_month[city_day_ahm["Month"][i]-1]

In [21]:
city_day_ahm

StationId  Year  Month  Date1       Date  PM2.5    PM10    NO    NO2  \
0         AP001  2017     11     24 2017-11-24  71.36  115.75  1.75  20.65   
1         AP001  2017     11     25 2017-11-25  81.40  124.50  1.44  20.50   
2         AP001  2017     11     26 2017-11-26  78.32  129.06  1.26  26.00   
3         AP001  2017     11     27 2017-11-27  88.76  135.32  6.60  30.85   
4         AP001  2017     11     28 2017-11-28  64.18  104.09  2.56  28.07   
...         ...   ...    ...    ...        ...    ...     ...   ...    ...   
99716     WB013  2020      4     27 2020-04-27  11.51   31.71  1.73  10.21   
99717     WB013  2020      4     28 2020-04-28   9.38   33.70  1.77  12.39   
99718     WB013  2020      4     29 2020-04-29  16.86   32.17  2.00  14.26   
99719     WB013  2020      4     30 2020-04-30  15.17   32.10  2.02  12.40   
99720     WB013  2020      5      1 2020-05-01  17.05   29.15  1.70  10.54   

         NOx    NH3    CO    SO2      O3  Benzene  Toluene  Xylene        AQI  \
0      12.40  12.19  0.10  10.76  109.26     0.17     5.92    0.10  272.27182   
1      12.08  10.72  0.12  15.24  127.09     0.20     6.50    0.06  184.00000   
2      14.85  10.28  0.14  26.96  117.44     0.22     7.95    0.08  197.00000   
3      21.77  12.91  0.11  33.59  111.81     0.29     7.63    0.12  198.00000   
4      17.01  11.42  0.09  19.00  138.18     0.17     5.02    0.07  188.00000   
...      ...    ...   ...    ...     ...      ...      ...     ...        ...   
99716  11.93  21.52  0.54   6.92   28.90     1.33     8.96     NaN   38.00000   
99717  14.15  22.44  0.64   6.09   26.34     1.35     9.47     NaN   39.00000   
99718  16.27  24.19  0.57   7.27   29.62     1.66    10.45     NaN   44.00000   
99719  14.41  25.58  0.61  11.53   33.93     0.96     8.92     NaN   46.00000   
99720  12.22  24.21  0.65   6.51   23.48     0.77     7.91     NaN   57.00000   

         AQI_Bucket  
0               NaN  
1          Moderate  
2          Moderate  
3          Moderate  
4          Moderate  
...             ...  
99716          Good  
99717          Good  
99718          Good  
99719          Good  
99720  Satisfactory  

[99721 rows x 19 columns]

In [22]:
city_day_ahm.isnull().sum()

StationId         0
Year              0
Month             0
Date1             0
Date              0
PM2.5         20737
PM10          41021
NO            16277
NO2           15764
NOx           14915
NH3           45811
CO            12491
SO2           23977
O3            24508
Benzene       29670
Toluene       36265
Xylene        79749
AQI               0
AQI_Bucket    20128
dtype: int64

In [23]:
#function for categorizing AQI values
def AQI_category(x):
    y = 0
    if x>=0 and x<=50:
        y = 1
    if x>50 and x<=100:
        y = 2
    if x>100 and x<=200:
        y = 3
    if x>200 and x<=300:
        y = 4
    if x>200 and x<=300:
        y = 5
    if x>300:
        y = 6
    return y

In [24]:
AQI_val = city_day_ahm.AQI_Bucket.unique()

In [25]:
AQI_val = AQI_val[1:]

In [26]:
length = len(city_day_ahm[city_day_ahm["Year"]!=2020])

In [29]:
X_train = []
Y_train = []
for i in range(80000):
    X_train.append(city_day_ahm["AQI"][i:i+7].values)
    Y_train.append( city_day_ahm["AQI"][i+7:i+7+1].values )
#converting to dataframe
X_train_df = pd.DataFrame(X_train)
Y_train_df = pd.DataFrame(Y_train)
X_train = X_train_df.values
Y_train = Y_train_df.values

In [30]:
X_train_df

0         1         2         3         4         5         6
0      272.27182  184.0000  197.0000  198.0000  188.0000  173.0000  165.0000
1      184.00000  197.0000  198.0000  188.0000  173.0000  165.0000  191.0000
2      197.00000  198.0000  188.0000  173.0000  165.0000  191.0000  191.0000
3      198.00000  188.0000  173.0000  165.0000  191.0000  191.0000  227.0000
4      188.00000  173.0000  165.0000  191.0000  191.0000  227.0000  168.0000
...          ...       ...       ...       ...       ...       ...       ...
79995  106.86170  106.8617   62.0000   52.0000   52.0000   34.0000  106.8617
79996  106.86170   62.0000   52.0000   52.0000   34.0000  106.8617   66.0000
79997   62.00000   52.0000   52.0000   34.0000  106.8617   66.0000   82.0000
79998   52.00000   52.0000   34.0000  106.8617   66.0000   82.0000   78.0000
79999   52.00000   34.0000  106.8617   66.0000   82.0000   78.0000   86.0000

[80000 rows x 7 columns]

In [31]:
X_test = city_day_ahm.AQI[80000:80007].values.reshape((1,7))

In [32]:
X_test

array([[ 34.        , 106.86170035,  66.        ,  82.        ,
         78.        ,  86.        , 100.        ]])

In [31]:
# city_day_ahm["AQI"][20006] , city_day_ahm["AQI"][20007]

(104.0, 94.0)

In [33]:
X_test

array([[ 34.        , 106.86170035,  66.        ,  82.        ,
         78.        ,  86.        , 100.        ]])

In [34]:
Y_test = city_day_ahm.AQI[80007].reshape((1,1))

In [35]:
X_train.shape,Y_train.shape,X_test.shape,Y_test.shape

((80000, 7), (80000, 1), (1, 7), (1, 1))

In [35]:
# X_test = []
# Y_test = []
# for i in range(30):
#     X_test.append(city_day_ahm["AQI"][24000+i:24000+i+60].values)
#     Y_test.append( city_day_ahm["AQI"][24000+i+60:24000+i+60+1].values)
# X_test_df = pd.DataFrame(X_test)
# Y_test_df = pd.DataFrame(Y_test)
# X_test = X_test_df.values
# Y_test = Y_test_df.values

In [36]:
# from sklearn.linear_model import LinearRegression
# dtregressor=LinearRegression()
# dtregressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [36]:
# # from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# dtregressor=DecisionTreeRegressor()
dtregressor=  RandomForestRegressor()
dtregressor.fit(X_train,Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [37]:
dtregressor.score(X_train ,Y_train)

0.9656485589403642

In [38]:
y_pred = dtregressor.predict(X_test)

In [39]:
y_pred

array([91.33304602])

In [40]:
y_pred,city_day_ahm.AQI[80007]

(array([91.33304602]), 103.0)

In [44]:
main(X_train,X_test,Y_train,Y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)
train acc
0.501657448823833
y_pred
testing acc
nan
DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')
train acc
0.976275153345473
y_pred
testing acc
nan
RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=40, n_jobs=None, oob_score=F

In [41]:
X_train.shape,Y_train.shape,X_test.shape,Y_test.shape

((80000, 7), (80000, 1), (1, 7), (1, 1))

In [42]:
# Predicting next n days
n = 100
n_past = 7
n_future = 1
x_input = city_day_ahm["AQI"][X_train.shape[0] : X_train.shape[0]+ 7].values 
x_input = x_input.reshape((1,7))              # reshape for applying model
output=[]
i=0
while(i<100):
    
    
    yhat = dtregressor.predict(x_input)      # yhat calulate
    

    
    output.append(yhat[0])                 # append to output
    
    x_input = np.append(x_input,yhat[0])
    

    x_input = x_input[1:]

    x_input = x_input.reshape((1,7))
    
    
    i = i+1
print(output)

[91.33304601698826, 97.32025045394448, 95.20468119153128, 92.14861700350761, 89.48, 97.52843741570206, 100.02318230563003, 96.79721967769295, 98.5937651322384, 100.31084554831706, 96.65721967769295, 99.78260846504932, 100.44031058678385, 100.03260846504932, 103.81687596317752, 103.1740411688249, 102.6660983884648, 96.0512495951885, 96.76093176035161, 98.49753026447681, 97.9, 98.05654545454544, 96.1237651322384, 96.97609838846479, 97.55445368470815, 96.95, 97.87159115281501, 97.84, 97.62, 97.09721967769296, 96.91721967769296, 96.74, 96.55721967769296, 96.71, 96.9, 96.99, 97.10721967769295, 97.22721967769296, 97.24721967769295, 97.23721967769296, 97.20721967769296, 97.05721967769296, 96.98721967769296, 96.86721967769296, 96.86721967769296, 96.87721967769295, 96.87721967769295, 97.02721967769295, 97.10721967769295, 97.24721967769295, 97.23721967769296, 97.20721967769296, 97.05721967769296, 96.98721967769296, 96.86721967769296, 96.86721967769296, 96.87721967769295, 96.87721967769295, 97.02

In [43]:
output = np.array(output)

a = city_day_ahm.AQI[80007:80107].values
a = pd.DataFrame(a,columns=["y_actual"])
a["y_pred"] = output
a.to_csv("abc4.csv")